import {geoPath,geoTransform} from 'https://cdn.jsdelivr.net/npm/d3-geo@3.1.1/+esm';
import {feature} from 'https://cdn.jsdelivr.net/npm/topojson-client@3.1.0/+esm';

const COLORS={C1:'var(--c1)',C2:'var(--c2)',C3:'var(--c3)',C4:'var(--c4)',NOISE:'var(--noise)',UNCLUSTERED:'var(--noise)'};
const HELP={
  clustered:'似た進路をシナリオ別に色分けします。細線は各メンバー、太線は各グループの代表となる中央値進路です。Noise判定は除いて表示します。',
  raw:'全アンサンブルメンバーを加工せず重ねます。モデルが持つ元の散らばりと、外れた進路をそのまま確認できます。',
  noise:'tracker jumpなど、物理的な進路とは限らない疑わしい線だけを隔離表示します。線をタップすると判定理由を確認できます。'
};
let data=null,land=null;
const NS='http://www.w3.org/2000/svg';
const svg=document.getElementById('plot'),title=document.getElementById('title'),subtitle=document.getElementById('subtitle'),discJa=document.getElementById('discJa'),discEn=document.getElementById('discEn'),metrics=document.getElementById('metrics'),clusters=document.getElementById('clusters'),detail=document.getElementById('detail'),view=document.getElementById('view'),hour=document.getElementById('hour'),hourLabel=document.getElementById('hourLabel'),legend=document.getElementById('legend'),controlHelp=document.getElementById('controlHelp'),mapStatus=document.getElementById('mapStatus');
function se(name,attrs={}){const n=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n}
function updateHelp(){controlHelp.innerHTML=`<strong>この操作で起こること</strong><p>${HELP[view.value]}<br><span>予報時刻スライダーを左へ動かすと、その時刻までに予測された軌道だけを表示します。</span></p>`}
async function loadMap(){try{const r=await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json',{cache:'force-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const world=await r.json();land=feature(world,world.objects.countries);mapStatus.textContent='海岸線: world-atlas / Natural Earth';if(data)render()}catch(e){mapStatus.textContent='海岸線を読み込めませんでした';console.warn('Basemap unavailable',e)}}
async function load(){loadMap();try{const r=await fetch('./data.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();setup();render()}catch(e){subtitle.textContent=`data.json を読み込めませんでした: ${e.message}`}}
function setup(){title.textContent=data.meta.title;subtitle.textContent=`${data.meta.model} • ${data.meta.storm} • init ${data.meta.init}`;discJa.textContent=data.disclaimer.ja;discEn.textContent=data.disclaimer.en;const maxHour=Math.max(...data.tracks.flatMap(t=>t.points.map(p=>p.fhour)));hour.max=maxHour;hour.value=maxHour;hourLabel.textContent=`+${maxHour}h`;metrics.innerHTML=[['Members',data.summary.members],['Scenario groups',data.summary.clusterCount],['Physical tracks',data.summary.cleanMembers],['Noise suspects',data.summary.noiseMembers]].map(([l,v])=>`<div class="metric"><small>${l}</small><b>${v}</b></div>`).join('');clusters.innerHTML=data.clusters.map(c=>`<div class="clusterCard" style="color:${COLORS[c.id]||COLORS.C4}"><div class="row"><b>${c.id}: ${c.label}</b><span>${c.share}%</span></div><small>${c.count} members</small><div class="bar"><i style="width:${c.share}%"></i></div></div>`).join('')+`<div class="clusterCard" style="color:var(--noise)"><div class="row"><b>Noise / tracker jump</b><span>${(data.summary.noiseMembers/data.summary.members*100).toFixed(1)}%</span></div></div>`;updateHelp();view.addEventListener('change',()=>{updateHelp();detail.textContent='地図上の線をタップしてください。';render()});hour.addEventListener('input',()=>{hourLabel.textContent=`+${hour.value}h`;render()})}
function bounds(){const pts=data.tracks.flatMap(t=>t.points).filter(p=>p.fhour<=Number(hour.value)),lats=pts.map(p=>p.lat),lons=pts.map(p=>p.lon);return{minLat:Math.floor(Math.min(...lats)-3),maxLat:Math.ceil(Math.max(...lats)+3),minLon:Math.floor(Math.min(...lons)-3),maxLon:Math.ceil(Math.max(...lons)+3)}}
function render(){if(!data)return;svg.innerHTML='';const b=bounds(),W=900,H=560,pad=50,centerLon=(b.minLon+b.maxLon)/2,unwrap=lon=>{while(lon-centerLon>180)lon-=360;while(lon-centerLon<-180)lon+=360;return lon},x=lon=>pad+(unwrap(lon)-b.minLon)/(b.maxLon-b.minLon)*(W-2*pad),y=lat=>H-pad-(lat-b.minLat)/(b.maxLat-b.minLat)*(H-2*pad);
  const defs=se('defs'),clip=se('clipPath',{id:'plotClip'});clip.appendChild(se('rect',{x:pad,y:pad,width:W-2*pad,height:H-2*pad}));defs.appendChild(clip);svg.appendChild(defs);svg.appendChild(se('rect',{x:pad,y:pad,width:W-2*pad,height:H-2*pad,class:'ocean'}));
  if(land){const transform=geoTransform({point(lon,lat){this.stream.point(x(lon),y(lat))}}),d=geoPath(transform)(land);if(d)svg.appendChild(se('path',{d,class:'land','clip-path':'url(#plotClip)'}))}
  for(let lon=Math.ceil(b.minLon/5)*5;lon<=b.maxLon;lon+=5){svg.appendChild(se('line',{x1:x(lon),y1:pad,x2:x(lon),y2:H-pad,class:'grid'}));const t=se('text',{x:x(lon)+3,y:H-pad+18,class:'axisText'});t.textContent=`${lon>180?lon-360:lon}°`;svg.appendChild(t)}for(let lat=Math.ceil(b.minLat/5)*5;lat<=b.maxLat;lat+=5){svg.appendChild(se('line',{x1:pad,y1:y(lat),x2:W-pad,y2:y(lat),class:'grid'}));const t=se('text',{x:5,y:y(lat)-3,class:'axisText'});t.textContent=`${lat}°`;svg.appendChild(t)}
  const tracksGroup=se('g',{'clip-path':'url(#plotClip)'}),mode=view.value;for(const tr of data.tracks){const noise=tr.cluster==='NOISE';if(mode==='noise'&&!noise)continue;if(mode==='clustered'&&noise)continue;const pts=tr.points.filter(p=>p.fhour<=Number(hour.value));if(pts.length<2)continue;const path=pts.map((p,i)=>`${i?'L':'M'}${x(p.lon).toFixed(1)},${y(p.lat).toFixed(1)}`).join(' '),node=se('path',{d:path,class:`track ${noise?'noiseTrack':''}`,stroke:COLORS[tr.cluster]||COLORS.C4,tabindex:'0','aria-label':`${tr.member} ${tr.cluster}`});node.addEventListener('click',()=>showDetail(tr));node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showDetail(tr)}});tracksGroup.appendChild(node)}if(mode==='clustered')for(const c of data.clusters){const pts=c.medianTrack.filter(p=>p.fhour<=Number(hour.value));if(pts.length<2)continue;tracksGroup.appendChild(se('path',{d:pts.map((p,i)=>`${i?'L':'M'}${x(p.lon).toFixed(1)},${y(p.lat).toFixed(1)}`).join(' '),class:'median',stroke:COLORS[c.id]||COLORS.C4}))}svg.appendChild(tracksGroup);legend.innerHTML=mode==='clustered'?data.clusters.map(c=>`<span style="color:${COLORS[c.id]||COLORS.C4}">${c.id} median + members</span>`).join(''):`<span style="color:var(--muted)">${mode==='noise'?'Likely tracker noise':'All member tracks'}</span>`}
function showDetail(tr){const last=tr.points.filter(p=>p.fhour<=Number(hour.value)).at(-1);detail.innerHTML=`<b>${tr.member}</b><br>Class: ${tr.cluster}<br>Last point: +${last?.fhour??'—'}h, ${last?.lat.toFixed(1)??'—'}°, ${last?.lon.toFixed(1)??'—'}°<br>MSLP: ${last?.mslp_hpa??'—'} hPa<br>${tr.noiseReasons.length?`Flags: ${tr.noiseReasons.join(', ')}`:'No tracker-jump flags detected.'}`}
load();