const COLORS={C1:'var(--c1)',C2:'var(--c2)',C3:'var(--c3)',C4:'var(--c4)',NOISE:'var(--noise)',UNCLUSTERED:'var(--noise)'};
const HELP={
  clustered:'似た進路をシナリオ別に色分けします。細線は各メンバー、太線は各グループの代表となる中央値進路です。Noise判定は除いて表示します。',
  raw:'全アンサンブルメンバーを加工せず重ねます。モデルが持つ元の散らばりと、外れた進路をそのまま確認できます。',
  noise:'tracker jumpなど、物理的な進路とは限らない疑わしい線だけを隔離表示します。線をタップすると判定理由を確認できます。'
};
let data=null,land=null;
const NS='http://www.w3.org/2000/svg';
const svg=document.getElementById('plot'),title=document.getElementById('title'),subtitle=document.getElementById('subtitle'),discJa=document.getElementById('discJa'),discEn=document.getElementById('discEn'),disclaimer=document.getElementById('disclaimer'),disclaimerDismiss=document.getElementById('disclaimerDismiss'),metrics=document.getElementById('metrics'),clusters=document.getElementById('clusters'),detail=document.getElementById('detail'),view=document.getElementById('view'),hour=document.getElementById('hour'),hourLabel=document.getElementById('hourLabel'),legend=document.getElementById('legend'),controlHelp=document.getElementById('controlHelp'),mapStatus=document.getElementById('mapStatus'),situationCards=document.getElementById('situationCards'),situationUpdated=document.getElementById('situationUpdated');
function se(name,attrs={}){const n=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n}
function updateHelp(){controlHelp.innerHTML=`<strong>この操作で起こること</strong><p>${HELP[view.value]}<br><span>予報時刻スライダーを左へ動かすと、その時刻までに予測された軌道だけを表示します。</span></p>`}
function toggleDisclaimer(){const collapsed=disclaimer.classList.toggle('collapsed');disclaimerDismiss.textContent=collapsed?'再表示 / Show notice':'わかりました / I understand';disclaimerDismiss.setAttribute('aria-expanded',String(!collapsed))}
function formatInit(init){const m=String(init).match(/^(\d{4})(\d{2})(\d{2})(\d{2})$/);if(!m)return String(init);const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3],+m[4]));const utc=`${m[1]}-${m[2]}-${m[3]} ${m[4]}Z`;const jst=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);return `${utc} / JST ${jst}`}
function japanVibe(){const clean=data.tracks.filter(t=>t.cluster!=='NOISE');if(!clean.length)return{pct:0,label:'判定不能'};const hits=clean.filter(t=>t.points.some(p=>p.lat>=24&&p.lat<=46&&p.lon>=128&&p.lon<=150)).length;const pct=Math.round(hits/clean.length*100);const label=pct>=75?'かなりある':pct>=55?'あるかも':pct>=35?'ちょっとある':pct>=15?'低め':'かなり低め';return{pct,label}}
function confidence(){const largest=Math.max(0,...data.clusters.map(c=>c.share));const cleanRatio=data.summary.members?data.summary.cleanMembers/data.summary.members:0;const score=Math.round(largest*cleanRatio);const stars=Math.max(1,Math.min(5,Math.ceil(score/20)));return{score,stars:`${'★'.repeat(stars)}${'☆'.repeat(5-stars)}`}}
function renderSituation(){const largest=[...data.clusters].sort((a,b)=>b.share-a.share)[0];const noisePct=data.summary.members?data.summary.noiseMembers/data.summary.members*100:0;const vibe=japanVibe(),conf=confidence();situationUpdated.textContent=formatInit(data.meta.init);const cards=[
  ['最大シナリオ',largest?`${largest.id} ${largest.label}`:'—',largest?`${largest.share}% / ${largest.count} members`:'' ],
  ['シナリオ数',String(data.summary.clusterCount),'物理的な進路群'],
  ['Noise率',`${noisePct.toFixed(1)}%`,`${data.summary.noiseMembers} / ${data.summary.members} members`],
  ['まとまり具合',conf.stars,`簡易スコア ${conf.score}/100`],
  ['日本に来そうな予感',`${vibe.label} (${vibe.pct}%)`,'実験的な解析結果です。公式の発表ではありません。']
];
  situationCards.innerHTML=cards.map(([label,value,note],i)=>`<article class="situationCard ${i===4?'japanVibe':''}"><small>${label}</small><strong>${value}</strong><span>${note}</span></article>`).join('')
}
async function loadMap(){try{const r=await fetch('./basemap.geojson',{cache:'force-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);land=await r.json();mapStatus.textContent='海岸線: Natural Earth（ローカル読込）';if(data)render()}catch(e){mapStatus.textContent='海岸線を読み込めませんでした';console.warn('Basemap unavailable',e);if(data)render()}}
async function load(){disclaimerDismiss.addEventListener('click',toggleDisclaimer);loadMap();try{const r=await fetch('./data.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();setup();render()}catch(e){subtitle.textContent=`data.json を読み込めませんでした: ${e.message}`}}
function setup(){title.textContent='西太平洋台風進路予測観測所';subtitle.textContent=`${data.meta.model} • ${data.meta.storm} • init ${data.meta.init}`;discJa.textContent=data.disclaimer.ja;discEn.textContent=data.disclaimer.en;const maxHour=Math.max(...data.tracks.flatMap(t=>t.points.map(p=>p.fhour)));hour.max=maxHour;hour.value=maxHour;hourLabel.textContent=`+${maxHour}h`;renderSituation();metrics.innerHTML=[['Members',data.summary.members],['Scenario groups',data.summary.clusterCount],['Physical tracks',data.summary.cleanMembers],['Noise suspects',data.summary.noiseMembers]].map(([l,v])=>`<div class="metric"><small>${l}</small><b>${v}</b></div>`).join('');clusters.innerHTML=data.clusters.map(c=>`<div class="clusterCard" style="color:${COLORS[c.id]||COLORS.C4}"><div class="row"><b>${c.id}: ${c.label}</b><span>${c.share}%</span></div><small>${c.count} members</small><div class="bar"><i style="width:${c.share}%"></i></div></div>`).join('')+`<div class="clusterCard" style="color:var(--noise)"><div class="row"><b>Noise / tracker jump</b><span>${(data.summary.noiseMembers/data.summary.members*100).toFixed(1)}%</span></div></div>`;updateHelp();view.addEventListener('change',()=>{updateHelp();detail.textContent='地図上の線をタップしてください。';render()});hour.addEventListener('input',()=>{hourLabel.textContent=`+${hour.value}h`;render()})}
function bounds(){const pts=data.tracks.flatMap(t=>t.points).filter(p=>p.fhour<=Number(hour.value)),lats=pts.map(p=>p.lat),lons=pts.map(p=>p.lon);return{minLat:Math.floor(Math.min(...lats)-3),maxLat:Math.ceil(Math.max(...lats)+3),minLon:Math.floor(Math.min(...lons)-3),maxLon:Math.ceil(Math.max(...lons)+3)}}
function polygonPath(coords,x,y){return coords.map(ring=>ring.map((p,i)=>`${i?'L':'M'}${x(p[0]).toFixed(1)},${y(p[1]).toFixed(1)}`).join(' ')+' Z').join(' ')}
function geometryPath(geometry,x,y){if(!geometry)return'';if(geometry.type==='Polygon')return polygonPath(geometry.coordinates,x,y);if(geometry.type==='MultiPolygon')return geometry.coordinates.map(poly=>polygonPath(poly,x,y)).join(' ');return''}
function render(){if(!data)return;svg.innerHTML='';const b=bounds(),W=900,H=560,pad=50,centerLon=(b.minLon+b.maxLon)/2,unwrap=lon=>{while(lon-centerLon>180)lon-=360;while(lon-centerLon<-180)lon+=360;return lon},x=lon=>pad+(unwrap(lon)-b.minLon)/(b.maxLon-b.minLon)*(W-2*pad),y=lat=>H-pad-(lat-b.minLat)/(b.maxLat-b.minLat)*(H-2*pad);
  const defs=se('defs'),clip=se('clipPath',{id:'plotClip'});clip.appendChild(se('rect',{x:pad,y:pad,width:W-2*pad,height:H-2*pad}));defs.appendChild(clip);svg.appendChild(defs);svg.appendChild(se('rect',{x:pad,y:pad,width:W-2*pad,height:H-2*pad,class:'ocean'}));
  if(land?.features){const mapGroup=se('g',{'clip-path':'url(#plotClip)'});for(const f of land.features){const d=geometryPath(f.geometry,x,y);if(d)mapGroup.appendChild(se('path',{d,class:'land'}))}svg.appendChild(mapGroup)}
  for(let lon=Math.ceil(b.minLon/5)*5;lon<=b.maxLon;lon+=5){svg.appendChild(se('line',{x1:x(lon),y1:pad,x2:x(lon),y2:H-pad,class:'grid'}));const t=se('text',{x:x(lon)+3,y:H-pad+18,class:'axisText'});t.textContent=`${lon>180?lon-360:lon}°`;svg.appendChild(t)}for(let lat=Math.ceil(b.minLat/5)*5;lat<=b.maxLat;lat+=5){svg.appendChild(se('line',{x1:pad,y1:y(lat),x2:W-pad,y2:y(lat),class:'grid'}));const t=se('text',{x:5,y:y(lat)-3,class:'axisText'});t.textContent=`${lat}°`;svg.appendChild(t)}
  const tracksGroup=se('g',{'clip-path':'url(#plotClip)'}),mode=view.value;for(const tr of data.tracks){const noise=tr.cluster==='NOISE';if(mode==='noise'&&!noise)continue;if(mode==='clustered'&&noise)continue;const pts=tr.points.filter(p=>p.fhour<=Number(hour.value));if(pts.length<2)continue;const path=pts.map((p,i)=>`${i?'L':'M'}${x(p.lon).toFixed(1)},${y(p.lat).toFixed(1)}`).join(' '),node=se('path',{d:path,class:`track ${noise?'noiseTrack':''}`,stroke:COLORS[tr.cluster]||COLORS.C4,tabindex:'0','aria-label':`${tr.member} ${tr.cluster}`});node.addEventListener('click',()=>showDetail(tr));node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showDetail(tr)}});tracksGroup.appendChild(node)}if(mode==='clustered')for(const c of data.clusters){const pts=c.medianTrack.filter(p=>p.fhour<=Number(hour.value));if(pts.length<2)continue;tracksGroup.appendChild(se('path',{d:pts.map((p,i)=>`${i?'L':'M'}${x(p.lon).toFixed(1)},${y(p.lat).toFixed(1)}`).join(' '),class:'median',stroke:COLORS[c.id]||COLORS.C4}))}svg.appendChild(tracksGroup);legend.innerHTML=mode==='clustered'?data.clusters.map(c=>`<span style="color:${COLORS[c.id]||COLORS.C4}">${c.id} median + members</span>`).join(''):`<span style="color:var(--muted)">${mode==='noise'?'Likely tracker noise':'All member tracks'}</span>`}
function showDetail(tr){const last=tr.points.filter(p=>p.fhour<=Number(hour.value)).at(-1);detail.innerHTML=`<b>${tr.member}</b><br>Class: ${tr.cluster}<br>Last point: +${last?.fhour??'—'}h, ${last?.lat.toFixed(1)??'—'}°, ${last?.lon.toFixed(1)??'—'}°<br>MSLP: ${last?.mslp_hpa??'—'} hPa<br>${tr.noiseReasons.length?`Flags: ${tr.noiseReasons.join(', ')}`:'No tracker-jump flags detected.'}`}
load();